FlatFileReader3.0/Models/Starcite.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

FlatFileReader3.0/Controllers/StarCiteController.cs
using FlatFileReader3._0.FileUploadClass;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FlatFileReader3._0.Controllers
{
    public class StarCiteController : Controller
    {
        // GET: StarCite
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase FileUpload, string delimiter = "")
        {
            if (FileUpload.ContentLength > 0)
            {
                try
                {
                    string fileName = Path.GetFileName(FileUpload.FileName);
                    string path = Path.Combine(Server.MapPath("~/App_Data"), fileName);
                    FileUpload.SaveAs(path);

                    int fileExtPos = fileName.LastIndexOf(".");
                    if (fileExtPos >= 0)
                        fileName = fileName.Substring(0, fileExtPos);
                    SplitSourceDBTable fileProcess = new SplitSourceDBTable();
                    DataTable dt = fileProcess.ReadCsv(path, delimiter, fileName);
                    SQLBulkCopy sQLBulkCopy = new SQLBulkCopy();
                    string str = sQLBulkCopy.ProcessBulkCopy(dt, fileName);
                    TempData["Success"] = fileName + " --- " + str;
                    System.IO.File.Delete(path);
                }
                catch (Exception ex)
                {
                    TempData["Fail"] = ex.Message;
                }
            }

            return View();
        }
    }
}

FlatFileReader3.0/Views/StarCite/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="contact">
    <div class="container">
        <div class="col-md-6">
            <div class="row">
                <div class="section-title">
                    <h2>Select Source File</h2>
                    <p>Please select the flat file which you want into extract.</p>
                </div>

                @using (Html.BeginForm("Index", "StarCite", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <input class="form-control" type="file" name="FileUpload" />
                    <br />
                    <label>Delimiter</label>
                    <input class="form-control" type="text" name="delimiter" />
                    <br />
                    <br />
                    <input class="btn btn-custom btn-lg" type="submit" name="Submit" id="Submit" value="Upload" />
                    <br />
                }
            </div>
            <div class="alert " id="outputmsg">
                @if (TempData["Success"] != null)
                {
                    <div class="alert alert-success" id="successMessage">@TempData["Success"]</div>
                }
                @if (TempData["Fail"] != null)
                {
                    <div class="alert alert-danger" id="failMsg">@TempData["Fail"]</div>
                }
            </div>
        </div>
        
    </div>

</div>
<script type="text/javascript">
    window.setTimeout(function () {
        // This will execute 5 seconds later
        var label = document.getElementById('outputmsg');
        if (label != null) {
            label.style.display = 'none';
        }
    }, 10000);
</script>